# Generated by Django 4.2 on 2025-10-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('batch_id', models.CharField(max_length=50, unique=True)),
                ('amla_input', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('slices_weight', models.DecimalField(decimal_places=3, max_digits=8)),
                ('sugar_added', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('marinated_weight', models.DecimalField(decimal_places=3, max_digits=8)),
                ('syrup_generated', models.DecimalField(decimal_places=3, max_digits=8)),
                ('final_weight', models.DecimalField(decimal_places=3, max_digits=8)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
