# Generated by Django 4.2 on 2025-10-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='amla_input',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='final_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='marinated_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='batch',
            name='slices_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='sugar_added',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='syrup_generated',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
